version: '3.9'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secure_pass_here
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]